/* This file was automatically generated by CasADi 3.6.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_impl_dae_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};

/* quadrotor_impl_dae_fun:(i0[13],i1[13],i2[4],i3[],i4[],i5[])->(o0[13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr;
  const casadi_real *cs;
  casadi_real *w0=w+0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, *w23=w+35;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 13, w0);
  /* #1: @1 = input[0][3] */
  w1 = arg[0] ? arg[0][3] : 0;
  /* #2: @2 = input[0][4] */
  w2 = arg[0] ? arg[0][4] : 0;
  /* #3: @3 = input[0][5] */
  w3 = arg[0] ? arg[0][5] : 0;
  /* #4: @4 = 37.037 */
  w4 = 3.7037037037037038e+01;
  /* #5: @5 = input[2][0] */
  w5 = arg[2] ? arg[2][0] : 0;
  /* #6: @6 = input[2][1] */
  w6 = arg[2] ? arg[2][1] : 0;
  /* #7: @7 = (@5+@6) */
  w7  = (w5+w6);
  /* #8: @8 = input[2][2] */
  w8 = arg[2] ? arg[2][2] : 0;
  /* #9: @7 = (@7+@8) */
  w7 += w8;
  /* #10: @9 = input[2][3] */
  w9 = arg[2] ? arg[2][3] : 0;
  /* #11: @7 = (@7+@9) */
  w7 += w9;
  /* #12: @4 = (@4*@7) */
  w4 *= w7;
  /* #13: @7 = input[0][6] */
  w7 = arg[0] ? arg[0][6] : 0;
  /* #14: @10 = (2.*@7) */
  w10 = (2.* w7 );
  /* #15: @11 = input[0][8] */
  w11 = arg[0] ? arg[0][8] : 0;
  /* #16: @10 = (@10*@11) */
  w10 *= w11;
  /* #17: @12 = input[0][7] */
  w12 = arg[0] ? arg[0][7] : 0;
  /* #18: @13 = (2.*@12) */
  w13 = (2.* w12 );
  /* #19: @14 = input[0][9] */
  w14 = arg[0] ? arg[0][9] : 0;
  /* #20: @13 = (@13*@14) */
  w13 *= w14;
  /* #21: @10 = (@10+@13) */
  w10 += w13;
  /* #22: @4 = (@4*@10) */
  w4 *= w10;
  /* #23: @10 = sq(@7) */
  w10 = casadi_sq( w7 );
  /* #24: @13 = sq(@12) */
  w13 = casadi_sq( w12 );
  /* #25: @10 = (@10+@13) */
  w10 += w13;
  /* #26: @13 = sq(@11) */
  w13 = casadi_sq( w11 );
  /* #27: @10 = (@10+@13) */
  w10 += w13;
  /* #28: @13 = sq(@14) */
  w13 = casadi_sq( w14 );
  /* #29: @10 = (@10+@13) */
  w10 += w13;
  /* #30: @4 = (@4/@10) */
  w4 /= w10;
  /* #31: @10 = -37.037 */
  w10 = -3.7037037037037038e+01;
  /* #32: @13 = (@5+@6) */
  w13  = (w5+w6);
  /* #33: @13 = (@13+@8) */
  w13 += w8;
  /* #34: @13 = (@13+@9) */
  w13 += w9;
  /* #35: @10 = (@10*@13) */
  w10 *= w13;
  /* #36: @13 = (2.*@7) */
  w13 = (2.* w7 );
  /* #37: @13 = (@13*@12) */
  w13 *= w12;
  /* #38: @15 = (2.*@11) */
  w15 = (2.* w11 );
  /* #39: @15 = (@15*@14) */
  w15 *= w14;
  /* #40: @13 = (@13-@15) */
  w13 -= w15;
  /* #41: @10 = (@10*@13) */
  w10 *= w13;
  /* #42: @13 = sq(@7) */
  w13 = casadi_sq( w7 );
  /* #43: @15 = sq(@12) */
  w15 = casadi_sq( w12 );
  /* #44: @13 = (@13+@15) */
  w13 += w15;
  /* #45: @15 = sq(@11) */
  w15 = casadi_sq( w11 );
  /* #46: @13 = (@13+@15) */
  w13 += w15;
  /* #47: @15 = sq(@14) */
  w15 = casadi_sq( w14 );
  /* #48: @13 = (@13+@15) */
  w13 += w15;
  /* #49: @10 = (@10/@13) */
  w10 /= w13;
  /* #50: @13 = -37.037 */
  w13 = -3.7037037037037038e+01;
  /* #51: @15 = (@5+@6) */
  w15  = (w5+w6);
  /* #52: @15 = (@15+@8) */
  w15 += w8;
  /* #53: @15 = (@15+@9) */
  w15 += w9;
  /* #54: @13 = (@13*@15) */
  w13 *= w15;
  /* #55: @15 = (2.*@12) */
  w15 = (2.* w12 );
  /* #56: @15 = (@15*@12) */
  w15 *= w12;
  /* #57: @16 = (2.*@11) */
  w16 = (2.* w11 );
  /* #58: @16 = (@16*@11) */
  w16 *= w11;
  /* #59: @15 = (@15+@16) */
  w15 += w16;
  /* #60: @16 = 1 */
  w16 = 1.;
  /* #61: @15 = (@15-@16) */
  w15 -= w16;
  /* #62: @13 = (@13*@15) */
  w13 *= w15;
  /* #63: @15 = sq(@7) */
  w15 = casadi_sq( w7 );
  /* #64: @16 = sq(@12) */
  w16 = casadi_sq( w12 );
  /* #65: @15 = (@15+@16) */
  w15 += w16;
  /* #66: @16 = sq(@11) */
  w16 = casadi_sq( w11 );
  /* #67: @15 = (@15+@16) */
  w15 += w16;
  /* #68: @16 = sq(@14) */
  w16 = casadi_sq( w14 );
  /* #69: @15 = (@15+@16) */
  w15 += w16;
  /* #70: @13 = (@13/@15) */
  w13 /= w15;
  /* #71: @15 = 9.81 */
  w15 = 9.8100000000000005e+00;
  /* #72: @13 = (@13-@15) */
  w13 -= w15;
  /* #73: @15 = input[0][10] */
  w15 = arg[0] ? arg[0][10] : 0;
  /* #74: @16 = (@15*@12) */
  w16  = (w15*w12);
  /* #75: @17 = 2 */
  w17 = 2.;
  /* #76: @16 = (@16/@17) */
  w16 /= w17;
  /* #77: @16 = (-@16) */
  w16 = (- w16 );
  /* #78: @17 = input[0][11] */
  w17 = arg[0] ? arg[0][11] : 0;
  /* #79: @18 = (@17*@11) */
  w18  = (w17*w11);
  /* #80: @19 = 2 */
  w19 = 2.;
  /* #81: @18 = (@18/@19) */
  w18 /= w19;
  /* #82: @16 = (@16-@18) */
  w16 -= w18;
  /* #83: @18 = input[0][12] */
  w18 = arg[0] ? arg[0][12] : 0;
  /* #84: @19 = (@18*@14) */
  w19  = (w18*w14);
  /* #85: @20 = 2 */
  w20 = 2.;
  /* #86: @19 = (@19/@20) */
  w19 /= w20;
  /* #87: @16 = (@16-@19) */
  w16 -= w19;
  /* #88: @19 = (@15*@7) */
  w19  = (w15*w7);
  /* #89: @20 = 2 */
  w20 = 2.;
  /* #90: @19 = (@19/@20) */
  w19 /= w20;
  /* #91: @20 = (@18*@11) */
  w20  = (w18*w11);
  /* #92: @21 = 2 */
  w21 = 2.;
  /* #93: @20 = (@20/@21) */
  w20 /= w21;
  /* #94: @19 = (@19+@20) */
  w19 += w20;
  /* #95: @20 = (@17*@14) */
  w20  = (w17*w14);
  /* #96: @21 = 2 */
  w21 = 2.;
  /* #97: @20 = (@20/@21) */
  w20 /= w21;
  /* #98: @19 = (@19-@20) */
  w19 -= w20;
  /* #99: @20 = (@17*@7) */
  w20  = (w17*w7);
  /* #100: @21 = 2 */
  w21 = 2.;
  /* #101: @20 = (@20/@21) */
  w20 /= w21;
  /* #102: @21 = (@18*@12) */
  w21  = (w18*w12);
  /* #103: @22 = 2 */
  w22 = 2.;
  /* #104: @21 = (@21/@22) */
  w21 /= w22;
  /* #105: @20 = (@20-@21) */
  w20 -= w21;
  /* #106: @14 = (@15*@14) */
  w14  = (w15*w14);
  /* #107: @21 = 2 */
  w21 = 2.;
  /* #108: @14 = (@14/@21) */
  w14 /= w21;
  /* #109: @20 = (@20+@14) */
  w20 += w14;
  /* #110: @7 = (@18*@7) */
  w7  = (w18*w7);
  /* #111: @14 = 2 */
  w14 = 2.;
  /* #112: @7 = (@7/@14) */
  w7 /= w14;
  /* #113: @12 = (@17*@12) */
  w12  = (w17*w12);
  /* #114: @14 = 2 */
  w14 = 2.;
  /* #115: @12 = (@12/@14) */
  w12 /= w14;
  /* #116: @7 = (@7+@12) */
  w7 += w12;
  /* #117: @11 = (@15*@11) */
  w11  = (w15*w11);
  /* #118: @12 = 2 */
  w12 = 2.;
  /* #119: @11 = (@11/@12) */
  w11 /= w12;
  /* #120: @7 = (@7-@11) */
  w7 -= w11;
  /* #121: @11 = 0.0397 */
  w11 = 3.9699999999999999e-02;
  /* #122: @12 = (@5-@6) */
  w12  = (w5-w6);
  /* #123: @12 = (@12-@8) */
  w12 -= w8;
  /* #124: @12 = (@12+@9) */
  w12 += w9;
  /* #125: @11 = (@11*@12) */
  w11 *= w12;
  /* #126: @12 = 1.4e-05 */
  w12 = 1.4000000000000000e-05;
  /* #127: @12 = (@12*@17) */
  w12 *= w17;
  /* #128: @12 = (@12*@18) */
  w12 *= w18;
  /* #129: @11 = (@11+@12) */
  w11 += w12;
  /* #130: @12 = 2.17e-05 */
  w12 = 2.1699999999999999e-05;
  /* #131: @12 = (@12*@17) */
  w12 *= w17;
  /* #132: @12 = (@12*@18) */
  w12 *= w18;
  /* #133: @11 = (@11-@12) */
  w11 -= w12;
  /* #134: @12 = 1.4e-05 */
  w12 = 1.4000000000000000e-05;
  /* #135: @11 = (@11/@12) */
  w11 /= w12;
  /* #136: @12 = 0.0397 */
  w12 = 3.9699999999999999e-02;
  /* #137: @14 = (-@5) */
  w14 = (- w5 );
  /* #138: @14 = (@14-@6) */
  w14 -= w6;
  /* #139: @14 = (@14+@8) */
  w14 += w8;
  /* #140: @14 = (@14+@9) */
  w14 += w9;
  /* #141: @12 = (@12*@14) */
  w12 *= w14;
  /* #142: @14 = 1.4e-05 */
  w14 = 1.4000000000000000e-05;
  /* #143: @14 = (@14*@15) */
  w14 *= w15;
  /* #144: @14 = (@14*@18) */
  w14 *= w18;
  /* #145: @12 = (@12-@14) */
  w12 -= w14;
  /* #146: @14 = 2.17e-05 */
  w14 = 2.1699999999999999e-05;
  /* #147: @14 = (@14*@15) */
  w14 *= w15;
  /* #148: @14 = (@14*@18) */
  w14 *= w18;
  /* #149: @12 = (@12+@14) */
  w12 += w14;
  /* #150: @14 = 1.4e-05 */
  w14 = 1.4000000000000000e-05;
  /* #151: @12 = (@12/@14) */
  w12 /= w14;
  /* #152: @14 = 0.0251266 */
  w14 = 2.5126582278481014e-02;
  /* #153: @5 = (@5-@6) */
  w5 -= w6;
  /* #154: @5 = (@5+@8) */
  w5 += w8;
  /* #155: @5 = (@5-@9) */
  w5 -= w9;
  /* #156: @14 = (@14*@5) */
  w14 *= w5;
  /* #157: @5 = 1.4e-05 */
  w5 = 1.4000000000000000e-05;
  /* #158: @5 = (@5*@15) */
  w5 *= w15;
  /* #159: @5 = (@5*@17) */
  w5 *= w17;
  /* #160: @14 = (@14+@5) */
  w14 += w5;
  /* #161: @5 = 1.4e-05 */
  w5 = 1.4000000000000000e-05;
  /* #162: @5 = (@5*@15) */
  w5 *= w15;
  /* #163: @5 = (@5*@17) */
  w5 *= w17;
  /* #164: @14 = (@14-@5) */
  w14 -= w5;
  /* #165: @5 = 2.17e-05 */
  w5 = 2.1699999999999999e-05;
  /* #166: @14 = (@14/@5) */
  w14 /= w5;
  /* #167: @23 = vertcat(@1, @2, @3, @4, @10, @13, @16, @19, @20, @7, @11, @12, @14) */
  rr=w23;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w10;
  *rr++ = w13;
  *rr++ = w16;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w7;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w14;
  /* #168: @0 = (@0-@23) */
  for (i=0, rr=w0, cs=w23; i<13; ++i) (*rr++) -= (*cs++);
  /* #169: output[0][0] = @0 */
  casadi_copy(w0, 13, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_impl_dae_fun_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_impl_dae_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_impl_dae_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_impl_dae_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_impl_dae_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_impl_dae_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    case 5: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_impl_dae_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 48;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
